name: Update Changelog
on:
  release:
    types: [published]
jobs:
  update-changelog:
    if: ${{contains(github.event.release.body, 'Agent Chart')}}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Charts Repo
        uses: actions/checkout@v2
        with:
          repository: liranfarage89/self-hosted
          ref: gh-pages
          path: './self-hosted'
          token: ${{ secrets.BOT_PAGES_TOKEN }}
      - name: Update CHANGELOG
        uses: bhowell2/github-substring-action@v1
        id: update-changelog
        with:
          value: ${{github.event.release.body}}
          index_of_str: Agent Chart
      - name: Format body # https://trstringer.com/github-actions-multiline-strings/
        run: |
          BODY=$(cat << EOF
          $(echo -n '.')          
          ## ${{ github.event.release.tag_name }}
          ${{ steps.update-changelog.outputs.substring }}
          EOF
          )
          echo "BODY<<EOF" >> $GITHUB_ENV
          echo "$BODY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Append to CHANGELOG
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ./self-hosted/CHANGELOG.md
          contents: |
            ${{env.BODY}}
          write-mode: append
      - name: Push CHANGELOG to repo
        uses: dmnemec/copy_file_to_another_repo_action@bbebd3da22e4a37d04dca5f782edd5201cb97083
        env:
          API_TOKEN_GITHUB: ${{ secrets.BOT_PAGES_TOKEN }}
        with:
          source_file: 'self-hosted/CHANGELOG.md'
          destination_repo: 'liranfarage89/self-hosted'
          user-email: 'self-hosted@env0.com'
          user_name: 'self-hosted'
          commit_message: '${{ env.GITHUB_REF }}'
          destination_branch: gh-pages
